spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost/zerg?characterEncoding=utf-8&useSSL=false
        username: root
        password:

        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
          prefix : /WEB-INF/jsp/
          suffix: .jsp
mybatis:
    mapper-Locations: classpath:mapping/*.xml
    typeAliasesPackage: com.wxsell.luffy
 #pattern:
 #  console: "%d - %msg%n"
 # path: D:/log/wxsell
 # file: D:/log/wxsell/log/sell.log
# 页面默认前缀目录



